import React, { use } from 'react';
import { Navbar } from '../Navbar/Navbar'
import Footer from '../Footer/Footer'
import MainHeader from '../MainHeader/MainHeader'
import Head from 'next/head';
import Announcement from '../Announcement/Announcement';
import SubscribePanel from '../SubscribePanel/SubscribPanel';
import InfoStrip from '../InfoStrip/InfoStrip';
import { usePathname } from 'next/navigation';

export default function Layout(props) {
    const { children, headers, announcement } = props;
    const pathname = usePathname();
    console.log(props)
    return (
        <div>
            <Head>
				<title>Charlees Comfort Kitchen</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href={"/images/img/logo2.png"} />
			</Head>
                            
            
            <main>
            <Navbar />
            <MainHeader header={headers} pathname={pathname} />
            {children}
            <SubscribePanel />
            <InfoStrip />
            <Footer />
            {/* {announcement.data.announcement ? <Announcement announcement={announcement} /> : null} */}
            </main>
           
        </div>
    )
}

