import '../styles/globals.css'
import Head from 'next/head'
import { Navbar } from '../components/Navbar/Navbar'
import SubscribePanel from '../components/SubscribePanel/SubscribPanel'
import InfoStrip from '../components/InfoStrip/InfoStrip'
import Footer from '../components/Footer/Footer'

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Charlees Comfort Kitchen</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={"/images/img/logo2.png"} />
      </Head>
      <Navbar />
      <Component {...pageProps} />
      <SubscribePanel />
      <InfoStrip />
      <Footer />
    </>
  )
}

export default MyApp
