import Head from 'next/head'
import { Navbar } from '../components/Navbar/Navbar'
import MainHeader from '../components/MainHeader/MainHeader'
import Footer from '../components/Footer/Footer'
import SubscribePanel from '../components/SubscribePanel/SubscribPanel'
import InfoStrip from '../components/InfoStrip/InfoStrip'
import About from '../components/About/About'

export default function Home() {
    const pageNumber = 2;
    const header = {
        title: "About",
        headline: "Info about our founders below",
        button: false
    };
    return (
        <div>
            <Head>
                <title>Charlees Comfort Kitchen</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href={"/images/favicon-2.ico"} />
            </Head>

            <main>
                <Navbar pageNumber={pageNumber} />
                <MainHeader header={header} />
                <About />
                <SubscribePanel />
                <InfoStrip />
            </main>
            <Footer />
        </div>
    )
}
