import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Navbar } from '../components/Navbar/Navbar'
import MainHeader from '../components/MainHeader/MainHeader'
import Menu from '../components/Menu/Menu'
import RestaurantIcon from '@mui/icons-material/Restaurant';
import Footer from '../components/Footer/Footer'
import SubscribePanel from '../components/SubscribePanel/SubscribPanel'
import InfoStrip from '../components/InfoStrip/InfoStrip'

export default function Home() {
    const pageNumber = 2;
    const header = "About";
    return (
        <div>
            <Head>
                <title>Charlees Comfort Kitchen</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href={"/images/favicon-2.ico"} />
            </Head>

            <main>
                <Navbar pageNumber={pageNumber} />
                <MainHeader header={header} />
                <div>
                    <div className="flex flex-col flex-wrap">
                        <div className="flex mx-auto">
                            <Image className="img-fluid mb-3 mb-lg-0"
                                src="/images/img/about-photo.jpg" alt="menu-1"
                                width={700}
                                height={799}
                            />
                        </div>
                        <div className="col-xl-4 col-lg-5">
                            <div className="text-white-50 featured-text text-center text-lg-left">
                                <h2>Ashley Jenkin and Matt LaFrance</h2>
                                <p className="text-white-50 mb-0">
                                    Matt and Ashley have a passion for cooking and creating incredible food. Between the
                                    two of them, they have over 40 years of combined experience cooking, learning on the
                                    job and schooling. While Matt is a graduate of The Culinary Institute of America,
                                    Ashley’s education was on the job training and books. Lots of books! She had the
                                    amazing opportunity to land a job as a prep cook at the sweet young age of 19 and
                                    instantly realized that kitchen people, are her people. By the age of 21, she had
                                    already earned the title of Pastry Chef at an award-winning restaurant in Las Vegas.
                                    And although her resume mostly reads Pastry Chef, Ashley is a sponge when it comes
                                    to learning about and cooking anything and everything. Nothing brings her more joy
                                    than tackling a new project and learning how to make something new and different.
                                    From desserts and breads to cuisines from other cultures and countries to highly
                                    technical pates, terrines and other charcuterie treats, Ashley loves to do it all!
                                </p>
                            </div>
                        </div>
                        <div className="row gx-0 mb-4 mb-lg-5 py-4 align-items-center text-white-50">
                            <p>
                                Matt got an even earlier start in the culinary world. His high school in New Hampshire
                                had the youngest chapter of the American Culinary Federation and lucky for us, he chose
                                to participate. He even landed the job as President of his chapter. From there, Matt
                                graduated early and headed straight to culinary school. While in school, his current
                                love for cooking grew even more. After graduating from CIA, he bounced around New
                                England a bit working as a cook until finding himself in upstate New York. After
                                spending several years there, Matt attended a job fair at his alma mater and met a Chef
                                from the Aspen area in Colorado who was recruiting for the winter ski season. He packed
                                up and moved halfway across the country where he worked hard and eventually earned the
                                Executive Sous Chef title working under an amazing Chef. Colorado is also where Matt and
                                Ashley met and have been a part of each other’s lives for almost a decade. First
                                friends, then more. These two are a culinary dream team!
                            </p>
                        </div>
                    </div>
                </div>
                <SubscribePanel />
                <InfoStrip />
            </main>
            <Footer />
        </div>
    )
}
