import MainHeader from '../components/MainHeader/MainHeader'
import Head from 'next/head';
import SubscribePanel from '../components/SubscribePanel/SubscribPanel'
import InfoStrip from '../components/InfoStrip/InfoStrip'
import { getInfoCards, getHeaders } from '../lib/api'


export default function Home({ preview, infoCards, headers }) {

    const page = 4

    return (
        <div>
            <Head>
                <title>Charlees Comfort Kitchen</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href={"/images/img/logo2.png"} />
            </Head>
            <main>
                <MainHeader header={headers} page={page} />
                <div className="flex justify-center py-20 mb-20 mx-4">
                    <iframe
                        src="https://calendar.google.com/calendar/embed?height=600&wkst=1&bgcolor=%23616161&ctz=America%2FDenver&showTabs=0&src=Y2hhcmxlZXNjb21mb3J0a2l0Y2hlbkBnbWFpbC5jb20&color=%23039BE5"
                        style={{ border: "solid 1px #777" }}
                        width="800"
                        height="600"
                        frameborder="0"
                        scrolling="no"></iframe>

                </div>
            </main>
            <SubscribePanel />
            <InfoStrip infoCards={infoCards} />
        </div>
    )
}


export async function getServerSideProps({ preview = true }) {
    const infoCards = (await getInfoCards(preview)) ?? []
    const headers = (await getHeaders(preview)) ?? []

    return {
        props: { preview, infoCards, headers },
    }
}

