import Head from 'next/head'
import { Navbar } from '../components/Navbar/Navbar'
import MainHeader from '../components/MainHeader/MainHeader'
import Footer from '../components/Footer/Footer'
import SubscribePanel from '../components/SubscribePanel/SubscribPanel'
import InfoStrip from '../components/InfoStrip/InfoStrip'

export default function Home() {
    const pageNumber = 3;
    const header = {
        title: "Calendar",
        headline: "Calendar of our events and specials below",
        button: true
    };

    return (
        <div>
            <Head>
                <title>Charlees Comfort Kitchen</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href={"/images/favicon-2.ico"} />
            </Head>

            <main>
                <Navbar pageNumber={pageNumber} />
                <MainHeader header={header} />
                <div class="flex justify-center py-20 mb-20">
                    <iframe
                        src="https://calendar.google.com/calendar/embed?height=600&wkst=1&bgcolor=%23616161&ctz=America%2FDenver&showTabs=0&src=Y2hhcmxlZXNjb21mb3J0a2l0Y2hlbkBnbWFpbC5jb20&color=%23039BE5"
                        style={{ border: "solid 1px #777" }}
                        width="800"
                        height="600"
                        frameborder="0"
                        scrolling="no"></iframe>

                </div>
                <SubscribePanel />
                <InfoStrip />
            </main>
            <Footer />
        </div>
    )
}
