import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Navbar } from '../components/Navbar/Navbar'
import MainHeader from '../components/MainHeader/MainHeader'
import Menu from '../components/Menu/Menu'
import RestaurantIcon from '@mui/icons-material/Restaurant';
import Footer from '../components/Footer/Footer'
import SubscribePanel from '../components/SubscribePanel/SubscribPanel'
import InfoStrip from '../components/InfoStrip/InfoStrip'

export default function Home() {
    const pageNumber = 1;
    const header = "Gallery";
    return (
        <div>
            <Head>
                <title>Charlees Comfort Kitchen</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href={"/images/favicon-2.ico"} />
            </Head>

            <main>
                <Navbar pageNumber={pageNumber} />
                <MainHeader header={header} />
                <SubscribePanel />
                <InfoStrip />
            </main>
            <Footer />
        </div>
    )
}
