import MainHeader from '../components/MainHeader/MainHeader'
import Menu from '../components/Menu/Menu'
import ImageCarousel from '../components/ImageCarousel/ImageCarousel'
import Head from 'next/head';

export default function Home() {
  const header = {
    title: "Charlees Comfort Kitchen",
    headline: "Homestyle cooking in the heart of Utah",
    button: true
  };

  return (
    <div>
      <Head>
        <title>Charlees Comfort Kitchen</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={"/images/img/logo2.png"} />
      </Head>
      <main>
        <MainHeader header={header} />
        <Menu />
        <ImageCarousel />
      </main>
    </div>
  )
}
