import MainHeader from '../components/MainHeader/MainHeader'
import Menu from '../components/Menu/Menu'
import ImageCarousel from '../components/ImageCarousel/ImageCarousel'
import Head from 'next/head';
import { getGalImages, getHeaders, getInfoCards, getMenu, getSpecials, getAnnouncement } from '../lib/api'

export default function Home({ preview, headers, menu, specials, galImages, announcement, }) {

  const page = 1

  return (
    <div>
      <Head>
        <title>Charlees Comfort Kitchen</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={"/images/img/logo2.png"} />
      </Head>
      <main>
        <MainHeader header={headers} page={page} />
        <Menu menu={menu} specials={specials} />
        <ImageCarousel galImages={galImages} />
      </main>
    </div>
  )
}

export async function getServerSideProps({ preview = true }) {
  const infoCards = (await getInfoCards(preview)) ?? []
  const headers = (await getHeaders(preview)) ?? []
  const menu = (await getMenu(preview)) ?? []
  const specials = (await getSpecials(preview)) ?? []
  const galImages = (await getGalImages(preview)) ?? []
  const announcement = (await getAnnouncement(preview)) ?? []

  return {
    props: { preview, infoCards, headers, menu, specials, galImages, announcement },
  }
}

